### ISSUE TITLE
Feedback for v2

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid19_ct_pillar2#3]
Some nice detailed feedback from @parksw3 for version 2. 

## Abstract

- “Pillar 2 COVID-19 cases” maybe give a period. A bit confused when this was until later on.
- “eopulation-level”
- “we found evidence that … meaningful” not sure what is meant by “explaining variation meaningful”? Are you saying that the covariates are able to explain a high proportion of variation?
- it’s not clear that Ct values can be used as a tool for surveillance and avoid biases with case counts when the previous sentence if about a model poorly explaining Ct values when incidence was changing. Not saying that I disagree with the value of Ct values, but the writing is just a bit confusing. Maybe need to be more specific about what kind of surveillance you mean.

## Introduction
- “At the population level this can translate to population-level changes over time” sounds redundant
- 3 million cases!! I feel like the richness of the data set is one of the main distinguishing factors of the study and can be highlighted in the abstract?

## Methods
- “3 millions unique Ct values” from how many unique cases/individuals? Based on the introduction, it sounds like one ct value per case but just curious…
- epidemic phases: unclear what you do in between… for example, Delta was increasing in June and decreasing in December. Do you throw out everything in between?
- case numbers per variant: is this something reported through the UK government or are you doing some sort of inferred cases (like multiplying positive cases with proportion variants)?

## Results
- Omicron VL increases with doses until 2 and then decreases back down… I wonder if this is due to some sort of correlational bias discussed above + differences in growth rates across vaccine statuses. 

## Misc
- There is a lot of “this” throughout the report. Would be clearer if you explicitly say what “this” refers to.

**Comment by sbfnk** [comment]
Thanks @parksw3! I've incorporated and added an acknowledgement.
